-- Not really sql statements, but shell lines uning sql statements passed to the ogr2ogr utility

=pgsql2shp -f /sfb/DADOS/car/imoveis -h subrede2.144 -u sfb car_nacional "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM   usr_geocar_aplicacao.imovel WHERE imovel.flg_ativo = TRUE"



ogr2ogr -f "ESRI Shapefile" imoveis.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM   usr_geocar_aplicacao.imovel WHERE imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000"



ogr2ogr -f "ESRI Shapefile" imoveis_500K.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM   usr_geocar_aplicacao.imovel WHERE imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND imovel.idt_imovel <= 500000"



ogr2ogr -f "ESRI Shapefile" imoveis_1KK.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM   usr_geocar_aplicacao.imovel WHERE imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND imovel.idt_imovel > 500000 AND imovel.idt_imovel <= 1000000"


ogr2ogr -f "ESRI Shapefile" imoveis_1p5KK.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM   usr_geocar_aplicacao.imovel WHERE imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND imovel.idt_imovel > 1000000 AND imovel.idt_imovel <= 1500000"

ogr2ogr -f "ESRI Shapefile" imoveis_3KK.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM   usr_geocar_aplicacao.imovel WHERE imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND EXTRACT( YEAR FROM imovel.dat_protocolo)>0 AND imovel.idt_imovel > 1500000"





ogr2ogr -f "ESRI Shapefile" temas_pontos.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "  rel_tema_imovel_ponto.idt_tema, rel_tema_imovel_ponto.idt_imovel,   rel_tema_imovel_ponto.the_geom,   rel_tema_imovel_ponto.idt_rel_tema_imovel, FROM  usr_geocar_aplicacao.imovel,   usr_geocar_aplicacao.rel_tema_imovel_ponto WHERE   imovel.idt_imovel = rel_tema_imovel_ponto.idt_imovel AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000"

ogr2ogr -f "ESRI Shapefile" temas_poligonos_500k.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql " SELECT rel_tema_imovel_poligono.idt_tema, rel_tema_imovel_poligono.idt_imovel,   rel_tema_imovel_poligono.the_geom,   rel_tema_imovel_poligono.idt_rel_tema_imovel FROM  usr_geocar_aplicacao.imovel,   usr_geocar_aplicacao.rel_tema_imovel_poligono WHERE   imovel.idt_imovel = rel_tema_imovel_poligono.idt_imovel AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND imovel.idt_imovel <= 500000"


MT

ogr2ogr -f "ESRI Shapefile" imoveis_MT.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT   imovel.idt_imovel,   imovel.cod_imovel,   imovel.cod_protocolo,  imovel.dat_protocolo,   imovel.ind_status_imovel,   imovel.ind_tipo_imovel,   imovel.cod_cpf_cadastrante,   imovel.nom_completo_cadastrante,  imovel.nom_imovel,   imovel.num_fracao_ideal,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,  imovel.geo_area_imovel,   imovel.cod_cep,   imovel.des_acesso,   imovel.cpf_responsavel FROM  usr_geocar_aplicacao.municipio, usr_geocar_aplicacao.imovel WHERE  imovel.idt_municipio = municipio.idt_municipio AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND municipio.cod_estado='MT'"

ogr2ogr -f "ESRI Shapefile" temas_pontos.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "  rel_tema_imovel_ponto.idt_tema, rel_tema_imovel_ponto.idt_imovel,   rel_tema_imovel_ponto.the_geom,   rel_tema_imovel_ponto.idt_rel_tema_imovel, FROM  usr_geocar_aplicacao.imovel,   usr_geocar_aplicacao.rel_tema_imovel_ponto WHERE   imovel.idt_imovel = rel_tema_imovel_ponto.idt_imovel AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000"

ogr2ogr -f "ESRI Shapefile" temas_poligonos_500k.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql " SELECT rel_tema_imovel_poligono.idt_tema, rel_tema_imovel_poligono.idt_imovel,   rel_tema_imovel_poligono.the_geom,   rel_tema_imovel_poligono.idt_rel_tema_imovel FROM  usr_geocar_aplicacao.imovel,   usr_geocar_aplicacao.rel_tema_imovel_poligono WHERE   imovel.idt_imovel = rel_tema_imovel_poligono.idt_imovel AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000 AND imovel.idt_imovel <= 500000"



ogr2ogr -f "CSV" MT_imoveis_pessoas.csv PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT  municipio.cod_estado,   imovel_pessoa.idt_imovel_pessoa AS idt_pess_i,  imovel_pessoa.idt_imovel,   imovel_pessoa.nom_completo,   imovel_pessoa.ind_tipo_pessoa,   imovel_pessoa.cod_cpf_cnpj,  imovel_pessoa.nom_fantasia,  imovel.cod_imovel FROM   usr_geocar_aplicacao.imovel,   usr_geocar_aplicacao.municipio,   usr_geocar_aplicacao.imovel_pessoa WHERE   imovel.idt_municipio = municipio.idt_municipio AND imovel_pessoa.idt_imovel = imovel.idt_imovel AND cod_estado='MT' AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000"


ogr2ogr -f "CSV" pessoa_imovel.csv  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT *  FROM   usr_geocar_aplicacao.imovel_pessoa"

ogr2ogr -f "CSV" dicionario_tema.csv  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT *  FROM   usr_geocar_aplicacao.tema"



ogr2ogr -f "ESRI Shapefile" MT_imoveis_pessoas.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT  municipio.cod_estado,   imovel_pessoa.idt_imovel_pessoa AS idt_pess_i,  imovel_pessoa.idt_imovel,   imovel_pessoa.nom_completo,   imovel_pessoa.ind_tipo_pessoa,   imovel_pessoa.cod_cpf_cnpj,  imovel_pessoa.nom_fantasia,  imovel.cod_imovel FROM   usr_geocar_aplicacao.imovel,   usr_geocar_aplicacao.municipio,   usr_geocar_aplicacao.imovel_pessoa WHERE   imovel.idt_municipio = municipio.idt_municipio AND imovel_pessoa.idt_imovel = imovel.idt_imovel AND cod_estado='MT' AND imovel.flg_ativo = TRUE AND EXTRACT( YEAR FROM imovel.dat_protocolo)<30000"



--- Contagens por Municipio



ogr2ogr -f "CSV" Municipios_MF.csv PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT CASE WHEN num_modulo_fiscal < 4 THEN '0 a 4 MF' WHEN num_modulo_fiscal >= 4  AND num_modulo_fiscal < 15 THEN '4 e 15 MF' WHEN num_modulo_fiscal >= 15 THEN 'superior a 15MF' END AS "MF", cod_estado, nom_municipio, COUNT(*) AS "totalMF",sum(num_area_imovel) as "area_ha" FROM (SELECT CASE WHEN CASE WHEN flg_ativo = TRUE AND dat_atualizacao > to_date('20/02/2016','dd/mm/yyyy') THEN 'AT' WHEN flg_ativo = TRUE THEN ind_status_imovel WHEN flg_ativo = FALSE THEN 'AT' END IN ('AT','PE') THEN num_modulo_fiscal END AS num_modulo_fiscal, i.num_area_imovel, m.cod_estado, m.nom_municipio FROM usr_geocar_aplicacao.imovel i, usr_geocar_aplicacao.municipio m WHERE m.idt_municipio = i.idt_municipio AND i.flg_ativo = TRUE AND i.ind_status_imovel = 'AT')  a  WHERE num_modulo_fiscal IS NOT NULL GROUP BY CASE WHEN num_modulo_fiscal < 4 THEN '0 a 4 MF' WHEN num_modulo_fiscal >= 4  AND num_modulo_fiscal < 15 THEN '4 e 15 MF' WHEN num_modulo_fiscal >= 15 THEN 'superior a 15MF' END, cod_estado, nom_municipio ORDER BY cod_estado, nom_municipio, CASE WHEN num_modulo_fiscal < 4 THEN '0 a 4 MF' WHEN num_modulo_fiscal >= 4  AND num_modulo_fiscal < 15 THEN '4 e 15 MF' WHEN num_modulo_fiscal >= 15 THEN 'superior a 15MF' END"


ogr2ogr -f "CSV" Municipios_Kfw.csv PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT CASE WHEN num_modulo_fiscal < 4 THEN '0 a 4 MF' WHEN num_modulo_fiscal >= 4  AND num_modulo_fiscal < 15 THEN '4 e 15 MF' WHEN num_modulo_fiscal >= 15 THEN 'superior a 15MF' END AS "MF", cod_estado, nom_municipio, COUNT(*) AS "total",sum(num_area_imovel) as "area_ha" FROM (SELECT CASE WHEN CASE WHEN flg_ativo = TRUE AND dat_atualizacao > to_date('20/02/2016','dd/mm/yyyy') THEN 'AT' WHEN flg_ativo = TRUE THEN ind_status_imovel WHEN flg_ativo = FALSE THEN 'AT' END IN ('AT','PE') THEN num_modulo_fiscal END AS num_modulo_fiscal, i.num_area_imovel, m.cod_estado, m.nom_municipio FROM usr_geocar_aplicacao.imovel i, usr_geocar_aplicacao.municipio m WHERE m.idt_municipio = i.idt_municipio AND i.flg_ativo = TRUE AND i.ind_status_imovel = 'AT')  a  WHERE num_modulo_fiscal IS NOT NULL AND ((cod_estado='MT' AND nom_municipio in ('Alto Boa Vista','Alto Paraguai','Apiacás','Araputanga','Aripuaná','Brasnorte','Canarana','Carlinda','Castanheira','Colíder','Colniza','Comodoro','Confresa','Cotriguaçu','Denise','Diamantino','Gaúcha do Norte',
'Guarantã do Norte','Itanhangá','Itaúba','Jauru','Juara','Juína','Marcelândia','Matupá','Nova Bandeirantes','Nova Canaã do Norte','Nova Guarita','Nova Lacerda','Nova Maringá','Nova Monte Verde',
'Nova Santa Helena','Novo Horizonte do Norte','Novo Mundo','Paranaíta','Peixoto de Azevedo','Pontes e Lacerda','Porto Alegre do Norte','Porto dos Gaúchos','Querência','Rio Branco','Santa Terezinha','São Félix do Araguaia','Tabaporã','Terra Nova do Norte','Vila Rica')) OR (cod_estado='PA' AND nom_municipio in ('Água Azul do Norte','Bannach','Brejo Grande do Araguaia','Conceição do Araguaia','Dom Eliseu Floresta do Araguaia','Ourilândia do Norte','Palestina do Pará','Piçarra','Redenção','Rio Maria','São Domingos do Araguaia','São Geraldo do Araguaia','São João do Araguaia','Sapucaia','Tucumã')) OR (cod_estado='RO'AND nom_municipio in ('Alto Paraíso','Buritis','Campo Novo','Cujubim','Nova Mamoré','Pimenta Bueno','Porto Velho') OR nom_municipio LIKE 'Itapuã D%Oeste'OR nom_municipio LIKE'Pau d%Arco'OR nom_municipio LIKE'Mirassol d%Oeste'OR nom_municipio LIKE'Machadinho d%Oeste')) GROUP BY CASE WHEN num_modulo_fiscal < 4 THEN '0 a 4 MF' WHEN num_modulo_fiscal >= 4  AND num_modulo_fiscal < 15 THEN '4 e 15 MF' WHEN num_modulo_fiscal >= 15 THEN 'superior a 15MF' END, cod_estado, nom_municipio ORDER BY cod_estado, nom_municipio, CASE WHEN num_modulo_fiscal < 4 THEN '0 a 4 MF' WHEN num_modulo_fiscal >= 4  AND num_modulo_fiscal < 15 THEN '4 e 15 MF' WHEN num_modulo_fiscal >= 15 THEN 'superior a 15MF' END"


---- baixar kfw

ogr2ogr -f "ESRI Shapefile" Municipios_Kfw.shp PG:"host=subrede.116 user=adm_usr dbname=car_nacional4" -sql "SELECT  i.idt_imovel,   i.cod_imovel,   i.ind_tipo_imovel,   i.idt_municipio, m.nom_municipio,   i.num_area_imovel,   i.num_modulo_fiscal,   i.dat_criacao,   i.dat_atualizacao,   i.flg_migracao, i.geo_area_imovel from  usr_geocar_aplicacao.municipio m,   usr_geocar_aplicacao.imovel i WHERE   (m.idt_municipio = i.idt_municipio AND i.flg_ativo=TRUE AND i.ind_status_imovel = 'AT') AND ((cod_estado='MT' AND nom_municipio in ('Alto Boa Vista','Alto Paraguai','Apiacás','Araputanga','Aripuaná','Brasnorte','Canarana','Carlinda','Castanheira','Colíder','Colniza','Comodoro','Confresa','Cotriguaçu','Denise','Diamantino','Gaúcha do Norte',
'Guarantã do Norte','Itanhangá','Itaúba','Jauru','Juara','Juína','Marcelândia','Matupá','Nova Bandeirantes','Nova Canaã do Norte','Nova Guarita','Nova Lacerda','Nova Maringá','Nova Monte Verde',
'Nova Santa Helena','Novo Horizonte do Norte','Novo Mundo','Paranaíta','Peixoto de Azevedo','Pontes e Lacerda','Porto Alegre do Norte','Porto dos Gaúchos','Querência','Rio Branco','Santa Terezinha','São Félix do Araguaia','Tabaporã','Terra Nova do Norte','Vila Rica')) OR (cod_estado='PA' AND nom_municipio in ('Água Azul do Norte','Bannach','Brejo Grande do Araguaia','Conceição do Araguaia','Dom Eliseu Floresta do Araguaia','Ourilândia do Norte','Palestina do Pará','Piçarra','Redenção','Rio Maria','São Domingos do Araguaia','São Geraldo do Araguaia','São João do Araguaia','Sapucaia','Tucumã')) OR (cod_estado='RO'AND nom_municipio in ('Alto Paraíso','Buritis','Campo Novo','Cujubim','Nova Mamoré','Pimenta Bueno','Porto Velho') OR nom_municipio LIKE 'Itapuã D%Oeste'OR nom_municipio LIKE'Pau d%Arco'OR nom_municipio LIKE'Mirassol d%Oeste'OR nom_municipio LIKE'Machadinho d%Oeste')) "

ogr2ogr -f "ESRI Shapefile" Municipios_Kfw_completo.shp PG:"host=subrede.116 user=adm_usr dbname=car_nacional4" -sql "SELECT  i.idt_imovel,   i.cod_imovel,   i.ind_tipo_i,    i.num_modulo,   i.dat_criaca,      i.shape from  usr_geocar_aplicacao.municipio m,   usr_geocar_aplicacao.imovel_jan2016 i WHERE   ((m.cod_estado='MT' AND nom_municipio in ('Alto Boa Vista','Alto Paraguai','Apiacás','Araputanga','Aripuaná','Brasnorte','Canarana','Carlinda','Castanheira','Colíder','Colniza','Comodoro','Confresa','Cotriguaçu','Denise','Diamantino','Gaúcha do Norte',
'Guarantã do Norte','Itanhangá','Itaúba','Jauru','Juara','Juína','Marcelândia','Matupá','Nova Bandeirantes','Nova Canaã do Norte','Nova Guarita','Nova Lacerda','Nova Maringá','Nova Monte Verde',
'Nova Santa Helena','Novo Horizonte do Norte','Novo Mundo','Paranaíta','Peixoto de Azevedo','Pontes e Lacerda','Porto Alegre do Norte','Porto dos Gaúchos','Querência','Rio Branco','Santa Terezinha','São Félix do Araguaia','Tabaporã','Terra Nova do Norte','Vila Rica')) OR (m.cod_estado='PA' AND nom_municipio in ('Água Azul do Norte','Bannach','Brejo Grande do Araguaia','Conceição do Araguaia','Dom Eliseu Floresta do Araguaia','Ourilândia do Norte','Palestina do Pará','Piçarra','Redenção','Rio Maria','São Domingos do Araguaia','São Geraldo do Araguaia','São João do Araguaia','Sapucaia','Tucumã')) OR (m.cod_estado='RO'AND nom_municipio in ('Alto Paraíso','Buritis','Campo Novo','Cujubim','Nova Mamoré','Pimenta Bueno','Porto Velho') OR nom_municipio LIKE 'Itapuã D%Oeste'OR nom_municipio LIKE'Pau d%Arco'OR nom_municipio LIKE'Mirassol d%Oeste'OR nom_municipio LIKE'Machadinho d%Oeste')) AND m.geo_localizacao && i.shape AND ST_Intersects(m.geo_localizacao, i.shape)"

---pará

ogr2ogr -f "ESRI Shapefile" Municipios_Kfw_PA.shp PG:"host=subrede.116 user=adm_usr dbname=car_nacional4" -sql "SELECT  i.idt_imovel,   i.cod_imovel,   i.ind_tipo_i,    i.num_modulo,   i.dat_criaca,      i.shape from  usr_geocar_aplicacao.municipio m,   usr_geocar_aplicacao.imovel_jan2016 i WHERE   ((m.cod_estado='PA' AND (nom_municipio in ('Água Azul do Norte','Bannach','Brejo Grande do Araguaia','Conceição do Araguaia','Dom Eliseu Floresta do Araguaia','Ourilândia do Norte','Palestina do Pará','Piçarra','Redenção','Rio Maria','São Domingos do Araguaia','São Geraldo do Araguaia','São João do Araguaia','Sapucaia','Tucumã') OR nom_municipio LIKE 'Itapuã D%Oeste'OR nom_municipio LIKE'Pau d%Arco'OR nom_municipio LIKE'Mirassol d%Oeste'OR nom_municipio LIKE'Machadinho d%Oeste'))) AND m.geo_localizacao && i.shape AND ST_Intersects(m.geo_localizacao, i.shape)"


---baixar 1 municipio

ogr2ogr -f "ESRI Shapefile" MT_confresa2.shp PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "select   imovel.idt_imovel,   imovel.cod_imovel,   imovel.ind_tipo_imovel,   imovel.idt_municipio,   imovel.num_area_imovel,   imovel.num_modulo_fiscal,   imovel.dat_criacao,   imovel.dat_atualizacao,   imovel.flg_migracao, imovel.geo_area_imovel from usr_geocar_aplicacao.imovel where idt_municipio = 5103353 AND flg_ativo=TRUE AND ind_status_imovel = 'AT'"


--- Municipios desmatamento banco =>> banco


   ogr2ogr -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede.116 user=adm_usr dbname=car_nacional4" -sql "SELECT  i.idt_imovel,   i.cod_imovel,   i.ind_tipo_imovel,   i.idt_municipio, m.nom_municipio,   i.num_area_imovel,   i.num_modulo_fiscal,   i.dat_criacao,   i.dat_atualizacao,   i.flg_migracao, i.geo_area_imovel from  usr_geocar_aplicacao.municipio m,   usr_geocar_aplicacao.imovel i WHERE   (m.idt_municipio = i.idt_municipio AND i.flg_ativo=TRUE AND i.ind_status_imovel = 'AT') AND (UPPER(nom_municipio) in ('LÁBREA','BOCA DO ACRE','AMARANTE DO MARANHÃO','GRAJAÚ','VILA RICA','SÃO FÉLIX DO ARAGUAIA','PORTO DOS GAÚCHOS','PEIXOTO DE AZEVEDO','PARANAÍTA','NOVA UBIRATÃ','NOVA MARINGÁ','NOVA BANDEIRANTES','JUÍNA','GAÚCHA DO NORTE','COTRIGUAÇU','CONFRESA','COLNIZA','ARIPUANÃ','JUARA','TAPURAH','SANTA CARMEM','CLÁUDIA','ALTO BOA VISTA','SÃO FÉLIX DO XINGU','SANTA MARIA DAS BARREIRAS','RONDON DO PARÁ','NOVO REPARTIMENTO','NOVO PROGRESSO','CUMARU DO NORTE','ALTAMIRA','PACAJÁ','MARABÁ','ITUPIRANGA','MOJU','SENADOR JOSÉ PORFÍRIO','ANAPU','PORTO VELHO','PIMENTA BUENO','NOVA MAMORÉ','MUCAJAÍ','QUERÊNCIA','MARCELÂNDIA','BRASNORTE','ALTA FLORESTA','FELIZ NATAL','ULIANÓPOLIS','SANTANA DO ARAGUAIA','PARAGOMINAS','DOM ELISEU','BRASIL NOVO','TAILÂNDIA') OR UPPER(nom_municipio) LIKE '%MACHADINHO%OESTE%') " -nln desmat_aaimoveis



 ogr2ogr -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 1   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('LÁBREA','BOCA DO ACRE','AMARANTE DO MARANHÃO','GRAJAÚ','VILA RICA','SÃO FÉLIX DO ARAGUAIA', 'PORTO DOS GAÚCHOS','PEIXOTO DE AZEVEDO','PARANAÍTA','NOVA UBIRATÃ','NOVA MARINGÁ', 'NOVA BANDEIRANTES','JUÍNA','GAÚCHA DO NORTE'))" -nln prior_desmat_cobertura_solo

 ogr2ogr -append -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 1   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('COTRIGUAÇU','CONFRESA','COLNIZA','ARIPUANÃ', 'JUARA','TAPURAH','SANTA CARMEM','CLÁUDIA','ALTO BOA VISTA','SÃO FÉLIX DO XINGU','SANTA MARIA DAS BARREIRAS', 'RONDON DO PARÁ','NOVO REPARTIMENTO','NOVO PROGRESSO','CUMARU DO NORTE'))" -nln prior_desmat_cobertura_solo

 ogr2ogr -append -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 1   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('ALTAMIRA','PACAJÁ','MARABÁ','ITUPIRANGA', 'MOJU','SENADOR JOSÉ PORFÍRIO','ANAPU','PORTO VELHO','PIMENTA BUENO','NOVA MAMORÉ','MUCAJAÍ','QUERÊNCIA','MARCELÂNDIA', 'BRASNORTE','ALTA FLORESTA','FELIZ NATAL','ULIANÓPOLIS', 'SANTANA DO ARAGUAIA','PARAGOMINAS','DOM ELISEU','BRASIL NOVO','TAILÂNDIA') OR UPPER(nom_municipio) LIKE '%MACHADINHO%OESTE%')" -nln prior_desmat_cobertura_solo








 ogr2ogr -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 3   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('LÁBREA','BOCA DO ACRE','AMARANTE DO MARANHÃO','GRAJAÚ','VILA RICA','SÃO FÉLIX DO ARAGUAIA', 'PORTO DOS GAÚCHOS','PEIXOTO DE AZEVEDO','PARANAÍTA','NOVA UBIRATÃ','NOVA MARINGÁ', 'NOVA BANDEIRANTES','JUÍNA','GAÚCHA DO NORTE','COTRIGUAÇU','CONFRESA','COLNIZA','ARIPUANÃ', 'JUARA','TAPURAH','SANTA CARMEM','CLÁUDIA','ALTO BOA VISTA','SÃO FÉLIX DO XINGU','SANTA MARIA DAS BARREIRAS', 'RONDON DO PARÁ','NOVO REPARTIMENTO','NOVO PROGRESSO','CUMARU DO NORTE','ALTAMIRA','PACAJÁ','MARABÁ','ITUPIRANGA', 'MOJU','SENADOR JOSÉ PORFÍRIO','ANAPU','PORTO VELHO','PIMENTA BUENO','NOVA MAMORÉ','MUCAJAÍ','QUERÊNCIA','MARCELÂNDIA', 'BRASNORTE','ALTA FLORESTA','FELIZ NATAL','ULIANÓPOLIS', 'SANTANA DO ARAGUAIA','PARAGOMINAS','DOM ELISEU','BRASIL NOVO','TAILÂNDIA') OR UPPER(nom_municipio) LIKE '%MACHADINHO%OESTE%')" -nln prior_desmat_reserva_legal



ogr2ogr -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 4   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('LÁBREA','BOCA DO ACRE','AMARANTE DO MARANHÃO','GRAJAÚ','VILA RICA','SÃO FÉLIX DO ARAGUAIA', 'PORTO DOS GAÚCHOS','PEIXOTO DE AZEVEDO','PARANAÍTA','NOVA UBIRATÃ','NOVA MARINGÁ', 'NOVA BANDEIRANTES','JUÍNA','GAÚCHA DO NORTE','COTRIGUAÇU','CONFRESA','COLNIZA','ARIPUANÃ', 'JUARA','TAPURAH','SANTA CARMEM','CLÁUDIA','ALTO BOA VISTA','SÃO FÉLIX DO XINGU','SANTA MARIA DAS BARREIRAS', 'RONDON DO PARÁ','NOVO REPARTIMENTO','NOVO PROGRESSO','CUMARU DO NORTE','ALTAMIRA','PACAJÁ','MARABÁ','ITUPIRANGA', 'MOJU','SENADOR JOSÉ PORFÍRIO','ANAPU','PORTO VELHO','PIMENTA BUENO','NOVA MAMORÉ','MUCAJAÍ','QUERÊNCIA','MARCELÂNDIA', 'BRASNORTE','ALTA FLORESTA','FELIZ NATAL','ULIANÓPOLIS', 'SANTANA DO ARAGUAIA','PARAGOMINAS','DOM ELISEU','BRASIL NOVO','TAILÂNDIA') OR UPPER(nom_municipio) LIKE '%MACHADINHO%OESTE%')" -nln prior_desmat_serv_adm

ogr2ogr -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 5   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('LÁBREA','BOCA DO ACRE','AMARANTE DO MARANHÃO','GRAJAÚ','VILA RICA','SÃO FÉLIX DO ARAGUAIA', 'PORTO DOS GAÚCHOS','PEIXOTO DE AZEVEDO','PARANAÍTA','NOVA UBIRATÃ','NOVA MARINGÁ', 'NOVA BANDEIRANTES','JUÍNA','GAÚCHA DO NORTE','COTRIGUAÇU','CONFRESA','COLNIZA','ARIPUANÃ', 'JUARA','TAPURAH','SANTA CARMEM','CLÁUDIA','ALTO BOA VISTA','SÃO FÉLIX DO XINGU','SANTA MARIA DAS BARREIRAS', 'RONDON DO PARÁ','NOVO REPARTIMENTO','NOVO PROGRESSO','CUMARU DO NORTE','ALTAMIRA','PACAJÁ','MARABÁ','ITUPIRANGA', 'MOJU','SENADOR JOSÉ PORFÍRIO','ANAPU','PORTO VELHO','PIMENTA BUENO','NOVA MAMORÉ','MUCAJAÍ','QUERÊNCIA','MARCELÂNDIA', 'BRASNORTE','ALTA FLORESTA','FELIZ NATAL','ULIANÓPOLIS', 'SANTANA DO ARAGUAIA','PARAGOMINAS','DOM ELISEU','BRASIL NOVO','TAILÂNDIA') OR UPPER(nom_municipio) LIKE '%MACHADINHO%OESTE%')" -nln prior_desmat_app

ogr2ogr -f "PostgreSQL" PG:"host=subrede.116 user=adm_usr dbname=car_nacional4 active_schema=public"  PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    tema.nom_tema,     rel_tema_imovel_poligono.the_geom,    rel_tema_imovel_poligono.num_area,    rel_tema_imovel_poligono.idt_imovel,    rel_tema_imovel_poligono.idt_tema,    municipio.nom_municipio,    municipio.cod_estado FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.tema,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.municipio WHERE    tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   municipio.idt_municipio = imovel.idt_municipio AND tema.idt_grupo = 3   AND (municipio.idt_municipio = imovel.idt_municipio AND   imovel.flg_ativo=TRUE AND imovel.ind_status_imovel = 'AT')  AND (UPPER(nom_municipio) in ('LÁBREA','BOCA DO ACRE','AMARANTE DO MARANHÃO','GRAJAÚ','VILA RICA','SÃO FÉLIX DO ARAGUAIA', 'PORTO DOS GAÚCHOS','PEIXOTO DE AZEVEDO','PARANAÍTA','NOVA UBIRATÃ','NOVA MARINGÁ', 'NOVA BANDEIRANTES','JUÍNA','GAÚCHA DO NORTE','COTRIGUAÇU','CONFRESA','COLNIZA','ARIPUANÃ', 'JUARA','TAPURAH','SANTA CARMEM','CLÁUDIA','ALTO BOA VISTA','SÃO FÉLIX DO XINGU','SANTA MARIA DAS BARREIRAS', 'RONDON DO PARÁ','NOVO REPARTIMENTO','NOVO PROGRESSO','CUMARU DO NORTE','ALTAMIRA','PACAJÁ','MARABÁ','ITUPIRANGA', 'MOJU','SENADOR JOSÉ PORFÍRIO','ANAPU','PORTO VELHO','PIMENTA BUENO','NOVA MAMORÉ','MUCAJAÍ','QUERÊNCIA','MARCELÂNDIA', 'BRASNORTE','ALTA FLORESTA','FELIZ NATAL','ULIANÓPOLIS', 'SANTANA DO ARAGUAIA','PARAGOMINAS','DOM ELISEU','BRASIL NOVO','TAILÂNDIA') OR UPPER(nom_municipio) LIKE '%MACHADINHO%OESTE%')" -nln prior_desmat_imovel



ogr2ogr -f "SQLite" sicabr_imoveis_20160428.sqlite PG:"host=subrede2.144 user=sfb dbname=car_nacional" -sql "SELECT    imovel.idt_imovel,    imovel.cod_imovel,    imovel.ind_tipo_origem,    imovel.ind_tipo_imovel,    imovel.idt_municipio,    imovel.num_area_imovel,    imovel.num_modulo_fiscal,    imovel.dat_criacao,    imovel.dat_atualizacao,    imovel.geo_area_imovel,    imovel.ind_status_imovel FROM    usr_geocar_aplicacao.imovel WHERE   idt_imovel<=$line AND imovel.flg_ativo = TRUE AND    imovel.ind_status_imovel IN ('AT','PE');"
                                                                                                        







