#!/bin/sh



ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN 1   ELSE 0  END) AS totalQtdCar,  SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN i.num_area_imovel   ELSE 0  END) AS totalSomaArea,  m.cod_estado FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND ((dat_criacao < to_date('01/03/2016','dd/mm/yyyy') AND ind_status_imovel IN ('AT','PE'))   OR (( (cod_imovel, dat_criacao) IN    (SELECT cod_imovel, max(dat_criacao)   FROM   usr_geocar_aplicacao.imovel i     WHERE  ind_status_imovel IN ('CA','RE') AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') AND dat_criacao < to_date('01/03/2016','dd/mm/yyyy')   GROUP BY cod_imovel)))) GROUP BY m.cod_estado ORDER BY m.cod_estado;" -nln relatorio_retro_ate20160229


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN 1   ELSE 0  END) AS totalQtdCar,  SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN i.num_area_imovel   ELSE 0  END) AS totalSomaArea,  m.cod_estado FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao >= to_date('05/05/2014','dd/mm/yyyy') AND ( dat_criacao < to_date('01/10/2015','dd/mm/yyyy') AND ind_status_imovel IN ('AT','PE'))   OR (( (cod_imovel, dat_criacao) IN    (SELECT cod_imovel, max(dat_criacao)   FROM   usr_geocar_aplicacao.imovel i     WHERE  ind_status_imovel IN ('CA','RE') AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') AND dat_criacao < to_date('01/10/2015','dd/mm/yyyy')   GROUP BY cod_imovel)))) GROUP BY m.cod_estado ORDER BY m.cod_estado;" -nln relatorio_retro_20151001a20140505


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN 1   ELSE 0  END) AS totalQtdCar,  SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN i.num_area_imovel   ELSE 0  END) AS totalSomaArea,  m.cod_estado FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao >= to_date('01/07/2015','dd/mm/yyyy') AND(dat_criacao < to_date('01/04/2016','dd/mm/yyyy') AND ind_status_imovel IN ('AT','PE'))   OR (( (cod_imovel, dat_criacao) IN    (SELECT cod_imovel, max(dat_criacao)   FROM   usr_geocar_aplicacao.imovel i     WHERE  ind_status_imovel IN ('CA','RE') AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') AND dat_criacao < to_date('01/04/2016','dd/mm/yyyy')   GROUP BY cod_imovel)))) GROUP BY m.cod_estado ORDER BY m.cod_estado;" -nln relatorio_retro_20160401a20150701


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT count(i.idt_imovel) AS totalQtdCar,  SUM(i.num_area_imovel) AS totalSomaArea,  m.cod_estado FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao < to_date('01/03/2016','dd/mm/yyyy'))  GROUP BY m.cod_estado ORDER BY m.cod_estado;" -nln relatorio_inicio_a20160229


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT count(i.idt_imovel) AS totalQtdCar,  SUM(i.num_area_imovel) AS totalSomaArea,  m.cod_estado FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao < to_date('01/10/2015','dd/mm/yyyy')) AND (dat_criacao >= to_date('05/05/2014','dd/mm/yyyy'))  GROUP BY m.cod_estado ORDER BY m.cod_estado;" -nln relatorio_20140505a20151001


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT count(i.idt_imovel) AS totalQtdCar,  SUM(i.num_area_imovel) AS totalSomaArea,  m.cod_estado FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao < to_date('01/07/2015','dd/mm/yyyy')) AND (dat_criacao >= to_date('01/04/2016','dd/mm/yyyy')) GROUP BY m.cod_estado ORDER BY m.cod_estado;" -nln relatorio_20160401a20150701


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN 1   ELSE 0  END) AS totalQtdCar,  SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN i.num_area_imovel   ELSE 0  END) AS totalSomaArea,  m.idt_municipio FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND ((dat_criacao < to_date('01/03/2016','dd/mm/yyyy') AND ind_status_imovel IN ('AT','PE'))   OR (( (cod_imovel, dat_criacao) IN    (SELECT cod_imovel, max(dat_criacao)   FROM   usr_geocar_aplicacao.imovel i     WHERE  ind_status_imovel IN ('CA','RE') AND dat_atualizacao >= to_date('01/03/2016','dd/mm/yyyy') AND dat_criacao < to_date('01/03/2016','dd/mm/yyyy')   GROUP BY cod_imovel)))) GROUP BY m.idt_municipio ORDER BY m.idt_municipio;" -nln relatorio_munic_retro_inicio_a20160229


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN 1   ELSE 0  END) AS totalQtdCar,  SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN i.num_area_imovel   ELSE 0  END) AS totalSomaArea,  m.idt_municipio FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao >= to_date('05/05/2014','dd/mm/yyyy') AND ( dat_criacao < to_date('01/10/2015','dd/mm/yyyy') AND ind_status_imovel IN ('AT','PE'))   OR (( (cod_imovel, dat_criacao) IN    (SELECT cod_imovel, max(dat_criacao)   FROM   usr_geocar_aplicacao.imovel i     WHERE  ind_status_imovel IN ('CA','RE') AND dat_atualizacao >= to_date('01/10/2015','dd/mm/yyyy') AND dat_criacao < to_date('01/10/2015','dd/mm/yyyy')   GROUP BY cod_imovel)))) GROUP BY m.idt_municipio ORDER BY m.idt_municipio;" -nln relatorio_munic_retro_20151001a20140505


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN 1   ELSE 0  END) AS totalQtdCar,  SUM(CASE    WHEN  CASE  WHEN flg_ativo = true AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'     WHEN flg_ativo = true THEN ind_status_imovel     WHEN flg_ativo = false AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') THEN 'AT'    END   IN ('AT','PE') THEN i.num_area_imovel   ELSE 0  END) AS totalSomaArea,  m.idt_municipio FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao >= to_date('01/07/2015','dd/mm/yyyy') AND(dat_criacao < to_date('01/04/2016','dd/mm/yyyy') AND ind_status_imovel IN ('AT','PE'))   OR (( (cod_imovel, dat_criacao) IN    (SELECT cod_imovel, max(dat_criacao)   FROM   usr_geocar_aplicacao.imovel i     WHERE  ind_status_imovel IN ('CA','RE') AND dat_atualizacao >= to_date('01/04/2016','dd/mm/yyyy') AND dat_criacao < to_date('01/04/2016','dd/mm/yyyy')   GROUP BY cod_imovel)))) GROUP BY m.idt_municipio ORDER BY m.idt_municipio;" -nln relatorio_munic_retro_20160401a20150701


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT count(i.idt_imovel) AS totalQtdCar,  SUM(i.num_area_imovel) AS totalSomaArea,  m.idt_municipio FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao < to_date('01/03/2016','dd/mm/yyyy'))  GROUP BY m.idt_municipio ORDER BY m.idt_municipio;" -nln relatorio_munic_inicio_a20160229


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT count(i.idt_imovel) AS totalQtdCar,  SUM(i.num_area_imovel) AS totalSomaArea,  m.idt_municipio FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao < to_date('01/10/2015','dd/mm/yyyy')) AND (dat_criacao >= to_date('05/05/2014','dd/mm/yyyy'))  GROUP BY m.idt_municipio ORDER BY m.idt_municipio;" -nln relatorio_munic_20140505a20151001


ogr2ogr -f "PostgreSQL" PG:"host=host.116 user=admincar dbname=banco4 active_schema=user_consultores" PG:"host=host.144 user=user dbname=banco" -sql "SELECT count(i.idt_imovel) AS totalQtdCar,  SUM(i.num_area_imovel) AS totalSomaArea,  m.idt_municipio FROM  usr_geocar_aplicacao.imovel i,   usr_geocar_aplicacao.municipio m WHERE  m.idt_municipio = i.idt_municipio  AND (dat_criacao < to_date('01/07/2015','dd/mm/yyyy')) AND (dat_criacao >= to_date('01/04/2016','dd/mm/yyyy')) GROUP BY m.idt_municipio ORDER BY m.idt_municipio;" -nln relatorio_munic_20160401a20150701

















