#!/bin/sh



		ogr2ogr -f "ESRI Shapefile" -update -append  rj_completo_imoveis.shp PG:"host=host.116 user=user dbname=banco052016"  -sql "SELECT    imovel.idt_imovel,    imovel.cod_imovel,    imovel.cod_protocolo,    rel_tema_imovel_poligono.idt_tema,    tema.nom_tema,   imovel.dat_protocolo,    imovel.ind_status_imovel,    imovel.ind_tipo_imovel,    imovel.cod_cpf_cadastrante,    imovel.nom_completo_cadastrante,    imovel.nom_imovel,    imovel.num_area_imovel as area_imovel, rel_tema_imovel_poligono.num_area as area_tema,    imovel.num_modulo_fiscal as num_mf,    imovel.dat_criacao,    imovel.dat_atualizacao,    municipio.idt_municipio,    municipio.nom_municipio,    municipio.cod_estado,    rel_tema_imovel_poligono.the_geom FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.municipio,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.tema WHERE    municipio.cod_estado='RJ' AND tema.idt_tema = 26 AND   municipio.idt_municipio = imovel.idt_municipio AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   tema.idt_tema = rel_tema_imovel_poligono.idt_tema;" -nln ecoterra_area_liquida POLYGON


ogr2ogr -f "ESRI Shapefile" -update -append  rj_completo_temas.shp PG:"host=host.116 user=user dbname=banco052016"  -sql "SELECT    imovel.idt_imovel,   rel_tema_imovel_poligono.idt_tema,    tema.nom_tema,  imovel.num_area_imovel as area_imovel, rel_tema_imovel_poligono.num_area as area_tema,   municipio.idt_municipio,   rel_tema_imovel_poligono.the_geom FROM    usr_geocar_aplicacao.imovel,    usr_geocar_aplicacao.municipio,    usr_geocar_aplicacao.rel_tema_imovel_poligono,    usr_geocar_aplicacao.tema WHERE    municipio.cod_estado='RJ' AND tema.idt_tema in (30,31,32,33,34,1,2,3,23,24,25,26,7,8,59,60) AND   municipio.idt_municipio = imovel.idt_municipio AND   rel_tema_imovel_poligono.idt_imovel = imovel.idt_imovel AND   tema.idt_tema = rel_tema_imovel_poligono.idt_tema AND GeometryType(the_geom)='MULTIPOLYGON';" -nln ecoterra_temas -nlt MULTIPOLYGON

